### ISSUE TITLE
Deployment stack Delete operation hangs up for a long time.

### ISSUE THREAD

**Issue by imran21** [Azure/deployment-stacks#179]
The Azure  Deploment Stack hags up for a longer time even after the resources got deleted.  Nearly for 2 hours.

Could anyone help on this at the earliest please.

I am just trying to delete the stack through Azre PowerShell Script
`Remove-AzSubscriptionDeploymentStack -Name $stackName -Confirm:$false   -Force`

This is being in a **Deleting** state for longer time

![image](https://github.com/user-attachments/assets/0fcf1ef0-0515-4a74-b727-a840b8bebdab)

**Comment by dantedallag** [comment]
@imran21 Could you please provide the correlation id for this delete?

**Comment by imran21** [comment]
> @imran21 Could you please provide the correlation id for this delete?

Hi @dantedallag  Please find the correlationId
"correlationId": "5a7e73db-9242-4ced-bda9-bfb4a455f7bc"

**Comment by imran21** [comment]
Hi @dantedallag Do you have any updates for me. Its been more that 3 hours it is deleting state.  Could you please help me at the earliest.

**Comment by snarkywolverine** [comment]
@imran21 Looks like the stack finished ~30 minutes ago, though the Microsoft.Security/pricings resources could not be deleted.  At this point, if you still want to delete the stack, you may want to detach the remaining resources (rather than delete them), and manually cleanup the remaining resources as applicable.  Meanwhile, we will have an internal discussion about how to handle that resource type going forward.

**Comment by snarkywolverine** [comment]
Hi @imran21 - After further discussion, we are going to leave this experience as-is. Because the resource can't be deleted, the deletion attempt will always fail the stack.  The stack will succeed deployment when those resources are detached (instead of deleted).

Let us know if you have any other questions!
